[workspace]

[package]
name = "wit-bindgen-symmetric-rt"
version = "0.36.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
wit-bindgen = { version = "0.36.0", path = "../../guest-rust" }

[features]
# always off feature
never = []
