[package]
name = "witx-bindgen-rust-impl"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
witx-bindgen-gen-core = { path = "../gen-core", version = "0.1" }
witx-bindgen-gen-rust-wasm = { path = "../gen-rust-wasm", version = "0.1" }

[features]
old-witx-compat = ['witx-bindgen-gen-core/old-witx-compat']
