[package]
name = "wit-bindgen-host-wasmtime-rust"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
bitflags = { workspace = true }
thiserror = "1.0"
wasmtime = { workspace = true }
wit-bindgen-host-wasmtime-rust-macro = { path = "../host-wasmtime-rust-macro", version = "0.2" }
tracing-lib = { version = "0.1.26", optional = true, package = 'tracing' }

[features]
# Enables generated code to emit events via the `tracing` crate whenever wasm is
# entered and when native functions are called. Note that tracing is currently
# only done for imported functions.
tracing = ['tracing-lib', 'wit-bindgen-host-wasmtime-rust-macro/tracing']
