[package]
name = "wit-bindgen-rust-macro"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.9.0"
edition.workspace = true
repository = 'https://github.com/bytecodealliance/wit-bindgen'
license = "Apache-2.0 WITH LLVM-exception"
homepage = 'https://github.com/bytecodealliance/wit-bindgen'
description = """
Procedural macro paired with the `wit-bindgen` crate.
"""

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
proc-macro2 = "1.0"
syn = "2.0"
wit-bindgen-core = { workspace = true }
wit-bindgen-rust = { workspace = true }
wit-bindgen-rust-lib = { workspace = true }
wit-component = { workspace = true }
anyhow = { workspace = true }
