[package]
name = "wit-bindgen-markdown"
version = "0.12.0"
edition.workspace = true
repository = 'https://github.com/bytecodealliance/wit-bindgen'
license = "Apache-2.0 WITH LLVM-exception"
homepage = 'https://github.com/bytecodealliance/wit-bindgen'
description = """
Markdown generator for WIT and the component model, typically used
through the `wit-bindgen-cli` crate.
"""

[lib]
doctest = false
test = false

[dependencies]
anyhow = { workspace = true }
heck = { workspace = true }
pulldown-cmark = { workspace = true }
clap = { workspace = true, optional = true }
wit-bindgen-core = { workspace = true }
wit-component = { workspace = true }
