[package]
name = "wit-bindgen-wasmtime"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bitflags = "1.2"
thiserror = "1.0"
wasmtime = "0.38.0"
wit-bindgen-wasmtime-impl = { path = "../wasmtime-impl", version = "0.1" }
tracing-lib = { version = "0.1.26", optional = true, package = 'tracing' }
async-trait = { version = "0.1.50", optional = true }

[features]
# Enables generated code to emit events via the `tracing` crate whenever wasm is
# entered and when native functions are called. Note that tracing is currently
# only done for imported functions.
tracing = ['tracing-lib', 'wit-bindgen-wasmtime-impl/tracing']

# Enables async support for generated code, although when enabled this still
# needs to be configured through the macro invocation.
async = ['async-trait', 'wit-bindgen-wasmtime-impl/async']
