[package]
name = "test-helpers"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2021"
publish = false

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
backtrace = "0.3"
heck = "0.3"
ignore = "0.4"
proc-macro2 = "1.0.27"
quote = "1.0.9"
wit-bindgen-core = { path = '../bindgen-core' }
wit-bindgen-gen-guest-rust = { path = '../gen-guest-rust', optional = true }
wit-bindgen-gen-host-wasmtime-rust = { path = '../gen-host-wasmtime-rust', optional = true }
wit-bindgen-gen-host-wasmtime-py = { path = '../gen-host-wasmtime-py', optional = true }
wit-bindgen-gen-host-js = { path = '../gen-host-js', optional = true }
wit-bindgen-gen-guest-c = { path = '../gen-guest-c', optional = true }
wit-bindgen-gen-guest-teavm-java = { path = '../gen-guest-teavm-java', optional = true }
wit-parser = { path = '../wit-parser' }
filetime = "0.2"

[build-dependencies]
wit-bindgen-gen-guest-c = { path = '../gen-guest-c' }
wit-bindgen-core = { path = '../bindgen-core' }

[features]
default = ['guest-rust', 'guest-c', 'host-js', 'host-wasmtime-py', 'host-wasmtime-rust']
guest-rust = ['wit-bindgen-gen-guest-rust']
guest-c = ['wit-bindgen-gen-guest-c']
guest-teavm-java = ['wit-bindgen-gen-guest-teavm-java']
host-js = ['wit-bindgen-gen-host-js']
host-wasmtime-py = ['wit-bindgen-gen-host-wasmtime-py']
host-wasmtime-rust = ['wit-bindgen-gen-host-wasmtime-rust']
