[package]
name = "test-helpers"
version.workspace = true
edition.workspace = true
publish = false

[lib]
doctest = false
test = false

[dependencies]
runtime-macro = { path = 'runtime-macro', optional = true }
codegen-macro = { path = 'codegen-macro' }
wit-bindgen-core = { workspace = true }
wit-parser = { workspace = true }
wit-component = { workspace = true, features = ['dummy-module'] }
wat = { workspace = true }
wasm-encoder = { workspace = true }

[features]
default = ['guest-rust', 'guest-c', 'guest-teavm-java']
guest-rust = ['runtime-macro?/guest-rust']
guest-c = ['runtime-macro?/guest-c']
guest-teavm-java = []#'runtime-macro?/guest-teavm-java']
