[package]
name = "wit-bindgen-rust"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
wit-bindgen-rust-impl = { path = "../rust-wasm-impl" }
async-trait = "0.1.51"
bitflags = "1.3"

[features]
witx-compat = ['wit-bindgen-rust-impl/witx-compat']
