[package]
name = "test-rust-wasm"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false

[dependencies]
witx-bindgen-rust = { path = "../rust-wasm", features = ['old-witx-compat'] }

[features]
unchecked = []

[[bin]]
name = "smoke"
test = false

[[bin]]
name = "numbers"
test = false

[[bin]]
name = "records"
test = false

[[bin]]
name = "variants"
test = false

[[bin]]
name = "lists"
test = false
