[package]
name = "test-rust-wasm"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition.workspace = true
publish = false

[dependencies]
wit-bindgen = { path = "../guest-rust" }

[lib]
test = false
doctest = false

[[bin]]
name = "results"
test = false

[[bin]]
name = "options"
test = false
