[package]
name = "test-rust-wasm"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition.workspace = true
publish = false

[dependencies]
wit-bindgen = { path = "../guest-rust" }
wit-bindgen-rt = { path = '../guest-rust/rt' }
rust-xcrate-test = { path = './rust-xcrate-test' }
futures = "0.3"
once_cell = "1.20"

[lib]
test = false
doctest = false

[[bin]]
name = "smoke"
test = false

[[bin]]
name = "numbers"
test = false

[[bin]]
name = "records"
test = false

[[bin]]
name = "variants"
test = false

[[bin]]
name = "lists"
test = false

[[bin]]
name = "flavorful"
test = false

[[bin]]
name = "many_arguments"
test = false

[[bin]]
name = "results"
test = false

[[bin]]
name = "options"
test = false

[[bin]]
name = "owning"
test = false

[[bin]]
name = "borrowing"
test = false

[[bin]]
name = "borrowing-duplicate-if-necessary"
test = false

[[bin]]
name = "resources"
test = false

[[bin]]
name = "resource_borrow_in_record"
test = false

[[bin]]
name = "resource_floats"
test = false

[[bin]]
name = "resource_import_and_export"
test = false

[[bin]]
name = "resource_with_lists"
test = false

[[bin]]
name = "resource_borrow_import"
test = false

[[bin]]
name = "resource_borrow_export"
test = false

[[bin]]
name = "resource_alias_redux"
test = false

[[bin]]
name = "resource_alias"
test = false

[[bin]]
name = "resource_aggregates"
test = false

[[bin]]
name = "resource_borrow_simple"
test = false

[[bin]]
name = "type_section_suffix"
test = false

[[bin]]
name = "rust_xcrate"
test = false
