[package]
name = "test-rust-wasm"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
wit-bindgen-guest-rust = { path = "../guest-rust" }

[features]
unchecked = []

[lib]
test = false
doctest = false

[[bin]]
name = "smoke"
test = false

[[bin]]
name = "numbers"
test = false

[[bin]]
name = "records"
test = false

[[bin]]
name = "unions"
test = false

[[bin]]
name = "variants"
test = false

[[bin]]
name = "lists"
test = false

[[bin]]
name = "flavorful"
test = false

[[bin]]
name = "many_arguments"
test = false

[[bin]]
name = "results"
test = false
