[package]
name = "test-rust-wasm"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
witx-bindgen-rust = { path = "../rust-wasm" }

[features]
unchecked = []
