[package]
name = "test-rust-wasm"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false

[dependencies]
futures-util = { version = "0.3.17", default-features = true }
wit-bindgen-rust = { path = "../rust-wasm" }

[features]
unchecked = []

[[bin]]
name = "smoke"
test = false

[[bin]]
name = "numbers"
test = false

[[bin]]
name = "records"
test = false

[[bin]]
name = "unions"
test = false

[[bin]]
name = "variants"
test = false

[[bin]]
name = "lists"
test = false

[[bin]]
name = "handles"
test = false

[[bin]]
name = "flavorful"
test = false

[[bin]]
name = "invalid"
test = false

[[bin]]
name = "async_functions"
test = false

[[bin]]
name = "many_arguments"
test = false
