[package]
name = "test-rust-wasm"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
wit-bindgen = { path = "../guest-rust" }

[lib]
test = false
doctest = false

[[bin]]
name = "smoke"
test = false

[[bin]]
name = "numbers"
test = false

[[bin]]
name = "records"
test = false

[[bin]]
name = "variants"
test = false

[[bin]]
name = "lists"
test = false

[[bin]]
name = "flavorful"
test = false

[[bin]]
name = "many_arguments"
test = false

[[bin]]
name = "results"
test = false

[[bin]]
name = "owning"
test = false

[[bin]]
name = "borrowing"
test = false

[[bin]]
name = "borrowing-duplicate-if-necessary"
test = false
