[package]
name = "wai-bindgen-gen-rust"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
wai-bindgen-gen-core = { path = '../gen-core' }
heck = "0.3"
