[package]
name = "aha-wit-bindgen-gen-core"
version = "0.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
wit-parser = { path = '../parser', package = "aha-wit-parser", version = "0.0.0"}
anyhow = "1"
