[package]
name = "witx-bindgen-gen-core"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
witx = { git = 'https://github.com/alexcrichton/WASI', branch = 'abi-next' }
