[package]
name = "wai-bindgen-gen-core"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
wai-parser = { path = '../parser' }
anyhow = "1"

[features]
witx-compat = ['wai-parser/witx-compat']
