[package]
name = "test-modules"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
wasmlink = { path = "../wasmlink" }
witx2 = { path = "../witx2" }

[dev-dependencies]
wasmtime = "0.28.0"
wasmtime-wasi = "0.28.0"
