[package]
name = "wit-bindgen-wasmtime-impl"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
wit-bindgen-gen-core = { path = "../gen-core", version = "0.1" }
wit-bindgen-gen-wasmtime = { path = "../gen-wasmtime", version = "0.1" }

[features]
tracing = []
async = []
